framework:
    notifier:
        chatter_transports:
<<<<<<< HEAD
            # Ajoutez vos transports (Slack, Telegram, etc.) si besoin
        texter_transports:
            # SMS, etc.
        channel_policy:
            # Ordre des canaux pour chaque type de notification
            urgent: ['email']
            high: ['browser']
            medium: ['browser']
            low: ['browser']
=======
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
>>>>>>> c5068dc4fcc54b142830cfad3e0547f2bfd72acd
