<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'banned_until' => [parent::class, 'banned_until', null, 16],
        "\0".parent::class."\0".'can_pin' => [parent::class, 'can_pin', null, 16],
        "\0".parent::class."\0".'dateNaissance' => [parent::class, 'dateNaissance', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'empreinte' => [parent::class, 'empreinte', null, 16],
        "\0".parent::class."\0".'idUtilisateur' => [parent::class, 'idUtilisateur', null, 16],
        "\0".parent::class."\0".'motDePasse' => [parent::class, 'motDePasse', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null, 16],
        "\0".parent::class."\0".'pointsFidelite' => [parent::class, 'pointsFidelite', null, 16],
        "\0".parent::class."\0".'pointsSolde' => [parent::class, 'pointsSolde', null, 16],
        "\0".parent::class."\0".'region' => [parent::class, 'region', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'stripeCustomerId' => [parent::class, 'stripeCustomerId', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'tokenVersion' => [parent::class, 'tokenVersion', null, 16],
        'banned_until' => [parent::class, 'banned_until', null, 16],
        'can_pin' => [parent::class, 'can_pin', null, 16],
        'dateNaissance' => [parent::class, 'dateNaissance', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'empreinte' => [parent::class, 'empreinte', null, 16],
        'idUtilisateur' => [parent::class, 'idUtilisateur', null, 16],
        'motDePasse' => [parent::class, 'motDePasse', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'photo' => [parent::class, 'photo', null, 16],
        'pointsFidelite' => [parent::class, 'pointsFidelite', null, 16],
        'pointsSolde' => [parent::class, 'pointsSolde', null, 16],
        'region' => [parent::class, 'region', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'stripeCustomerId' => [parent::class, 'stripeCustomerId', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'tokenVersion' => [parent::class, 'tokenVersion', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
