<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Partenaire extends \App\Entity\Partenaire implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'dateDemande' => [parent::class, 'dateDemande', null, 16],
        "\0".parent::class."\0".'dateValidation' => [parent::class, 'dateValidation', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'idUtilisateur' => [parent::class, 'idUtilisateur', null, 16],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'dateDemande' => [parent::class, 'dateDemande', null, 16],
        'dateValidation' => [parent::class, 'dateValidation', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'idUtilisateur' => [parent::class, 'idUtilisateur', null, 16],
        'logo' => [parent::class, 'logo', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
