<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class QuizResult extends \App\Entity\QuizResult implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'certificate' => [parent::class, 'certificate', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'percentage' => [parent::class, 'percentage', null, 16],
        "\0".parent::class."\0".'quiz' => [parent::class, 'quiz', null, 16],
        "\0".parent::class."\0".'score' => [parent::class, 'score', null, 16],
        "\0".parent::class."\0".'startedAt' => [parent::class, 'startedAt', null, 16],
        "\0".parent::class."\0".'submittedAt' => [parent::class, 'submittedAt', null, 16],
        "\0".parent::class."\0".'totalQuestions' => [parent::class, 'totalQuestions', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'certificate' => [parent::class, 'certificate', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'percentage' => [parent::class, 'percentage', null, 16],
        'quiz' => [parent::class, 'quiz', null, 16],
        'score' => [parent::class, 'score', null, 16],
        'startedAt' => [parent::class, 'startedAt', null, 16],
        'submittedAt' => [parent::class, 'submittedAt', null, 16],
        'totalQuestions' => [parent::class, 'totalQuestions', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
