<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \App\Entity\Produit implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'disponible' => [parent::class, 'disponible', null, 16],
        "\0".parent::class."\0".'idProduit' => [parent::class, 'idProduit', null, 16],
        "\0".parent::class."\0".'idVendeuse' => [parent::class, 'idVendeuse', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'quantite' => [parent::class, 'quantite', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'disponible' => [parent::class, 'disponible', null, 16],
        'idProduit' => [parent::class, 'idProduit', null, 16],
        'idVendeuse' => [parent::class, 'idVendeuse', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'photo' => [parent::class, 'photo', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'quantite' => [parent::class, 'quantite', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
