<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4rCVEkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4r_CVEk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4r_CVEk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'favoriRepo' => ['privates', 'App\\Repository\\FavoriRepository', 'getFavoriRepositoryService', true],
        ], [
            'favoriRepo' => 'App\\Repository\\FavoriRepository',
        ]);
    }
}
