<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5A2xTDxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5A2xTDx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5A2xTDx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visitorActivityRepository' => ['privates', 'App\\Repository\\VisitorActivityRepository', 'getVisitorActivityRepositoryService', true],
        ], [
            'visitorActivityRepository' => 'App\\Repository\\VisitorActivityRepository',
        ]);
    }
}
