<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AjErm5QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ajErm5Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ajErm5Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assistant' => ['privates', 'App\\Service\\AIAssistant', 'getAIAssistantService', true],
        ], [
            'assistant' => 'App\\Service\\AIAssistant',
        ]);
    }
}
