<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EsvQdubService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.esvQdub' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'codeService' => ['privates', 'App\\Service\\SmsCodeService', 'getSmsCodeServiceService', true],
            'loginAttemptService' => ['privates', 'App\\Security\\LoginAttemptService', 'getLoginAttemptServiceService', true],
        ], [
            'codeService' => 'App\\Service\\SmsCodeService',
            'loginAttemptService' => 'App\\Security\\LoginAttemptService',
        ]);

        if (isset($container->privates['.service_locator.esvQdub'])) {
            return $container->privates['.service_locator.esvQdub'];
        }

        return $container->privates['.service_locator.esvQdub'] = $instance;
    }
}
