<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_73s6gacService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.73s6gac' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.73s6gac'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandRepository' => ['privates', 'App\\Repository\\CommandRepository', 'getCommandRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'livraisonRepository' => ['privates', 'App\\Repository\\LivraisonRepository', 'getLivraisonRepositoryService', true],
            'livreurRepository' => ['privates', 'App\\Repository\\LivreurRepository', 'getLivreurRepositoryService', true],
        ], [
            'commandRepository' => 'App\\Repository\\CommandRepository',
            'entityManager' => '?',
            'livraisonRepository' => 'App\\Repository\\LivraisonRepository',
            'livreurRepository' => 'App\\Repository\\LivreurRepository',
        ]);
    }
}
