<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAIQuizGeneratorServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AIQuizGeneratorService' shared autowired service.
     *
     * @return \App\Service\AIQuizGeneratorService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AIQuizGeneratorService.php';

        return $container->privates['App\\Service\\AIQuizGeneratorService'] = new \App\Service\AIQuizGeneratorService(($container->services['Symfony\\Contracts\\HttpClient\\HttpClientInterface'] ?? $container->load('getHttpClientInterfaceService')), ($container->privates['logger'] ?? self::getLoggerService($container)), $container->getEnv('default::OPENAI_API_KEY'));
    }
}
