<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAIAssistantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AIAssistant' shared autowired service.
     *
     * @return \App\Service\AIAssistant
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AIAssitant.php';

        return $container->privates['App\\Service\\AIAssistant'] = new \App\Service\AIAssistant(($container->services['Symfony\\Contracts\\HttpClient\\HttpClientInterface'] ?? $container->load('getHttpClientInterfaceService')), $container->getEnv('GEMINI_API_KEY'));
    }
}
