<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiQuizControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApiQuizController' shared autowired service.
     *
     * @return \App\Controller\ApiQuizController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ApiQuizController.php';

        $container->services['App\\Controller\\ApiQuizController'] = $instance = new \App\Controller\ApiQuizController(($container->privates['App\\Repository\\FormationRepository'] ?? $container->load('getFormationRepositoryService')), ($container->privates['App\\Repository\\QuizRepository'] ?? $container->load('getQuizRepositoryService')), ($container->privates['App\\Repository\\QuestionRepository'] ?? $container->load('getQuestionRepositoryService')), ($container->privates['App\\Repository\\CertificateRepository'] ?? $container->load('getCertificateRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\CertificateService'] ?? $container->load('getCertificateServiceService')), ($container->privates['App\\Service\\AIQuizGeneratorService'] ?? $container->load('getAIQuizGeneratorServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ApiQuizController', $container));

        return $instance;
    }
}
