<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientLivraisonControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ClientLivraisonController' shared autowired service.
     *
     * @return \App\Controller\ClientLivraisonController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ClientLivraisonController.php';

        $container->services['App\\Controller\\ClientLivraisonController'] = $instance = new \App\Controller\ClientLivraisonController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\CommandRepository'] ?? $container->load('getCommandRepositoryService')), ($container->privates['App\\Repository\\LivraisonRepository'] ?? $container->load('getLivraisonRepositoryService')), ($container->privates['App\\Repository\\LivreurRepository'] ?? $container->load('getLivreurRepositoryService')), ($container->privates['App\\Repository\\ProduitRepository'] ?? $container->load('getProduitRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ClientLivraisonController', $container));

        return $instance;
    }
}
