<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeCartHydratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CommandeCartHydrator' shared autowired service.
     *
     * @return \App\Service\CommandeCartHydrator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CommandeCartHydrator.php';

        return $container->privates['App\\Service\\CommandeCartHydrator'] = new \App\Service\CommandeCartHydrator(($container->privates['App\\Repository\\ProduitRepository'] ?? $container->load('getProduitRepositoryService')), ($container->privates['App\\Repository\\LigneCommandePlatRepository'] ?? $container->load('getLigneCommandePlatRepositoryService')));
    }
}
