<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginFailureListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\LoginFailureListener' shared autowired service.
     *
     * @return \App\Security\LoginFailureListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'LoginFailureListener.php';

        return $container->privates['App\\Security\\LoginFailureListener'] = new \App\Security\LoginFailureListener(($container->privates['App\\Security\\LoginAttemptService'] ?? $container->load('getLoginAttemptServiceService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
