<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSuccessListener2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\LoginSuccessListener' shared autowired service.
     *
     * @return \App\Security\LoginSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'LoginSuccessListener.php';

        return $container->privates['App\\Security\\LoginSuccessListener'] = new \App\Security\LoginSuccessListener(($container->privates['App\\Security\\LoginAttemptService'] ?? $container->load('getLoginAttemptServiceService')));
    }
}
