<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifier_TransportFactory_FreemobileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'notifier.transport_factory.free-mobile' shared service.
     *
     * @return \Symfony\Component\Notifier\Bridge\FreeMobile\FreeMobileTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'notifier'.\DIRECTORY_SEPARATOR.'Transport'.\DIRECTORY_SEPARATOR.'TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'notifier'.\DIRECTORY_SEPARATOR.'Transport'.\DIRECTORY_SEPARATOR.'AbstractTransportFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'free-mobile-notifier'.\DIRECTORY_SEPARATOR.'FreeMobileTransportFactory.php';

        return $container->privates['notifier.transport_factory.free-mobile'] = new \Symfony\Component\Notifier\Bridge\FreeMobile\FreeMobileTransportFactory(($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->services['Symfony\\Contracts\\HttpClient\\HttpClientInterface'] ?? $container->load('getHttpClientInterfaceService')));
    }
}
