<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartenaireControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PartenaireController' shared autowired service.
     *
     * @return \App\Controller\PartenaireController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'PartenaireController.php';

        $container->services['App\\Controller\\PartenaireController'] = $instance = new \App\Controller\PartenaireController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\PartenaireRepository'] ?? $container->load('getPartenaireRepositoryService')), ($container->privates['App\\Repository\\PlatRepository'] ?? $container->load('getPlatRepositoryService')), ($container->privates['App\\Service\\RecommendationService'] ?? $container->load('getRecommendationServiceService')), ($container->privates['App\\Repository\\CollaborationProduitRepository'] ?? $container->load('getCollaborationProduitRepositoryService')), ($container->privates['App\\Repository\\ProduitRepository'] ?? $container->load('getProduitRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PartenaireController', $container));

        return $instance;
    }
}
