<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecompenseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RecompenseController' shared autowired service.
     *
     * @return \App\Controller\RecompenseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'RecompenseController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RecompenseService.php';

        $container->services['App\\Controller\\RecompenseController'] = $instance = new \App\Controller\RecompenseController(($container->privates['App\\Service\\PointsFideliteService'] ?? $container->load('getPointsFideliteServiceService')), new \App\Service\RecompenseService(($container->privates['App\\Repository\\RecompenseRepository'] ?? $container->load('getRecompenseRepositoryService')), ($container->privates['App\\Repository\\RecompenseUtilisateurRepository'] ?? $container->load('getRecompenseUtilisateurRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\RecompenseController', $container));

        return $instance;
    }
}
