<?php

namespace ContainerM4eqg90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmsCodeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SmsCodeService' shared autowired service.
     *
     * @return \App\Service\SmsCodeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SmsCodeService.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\SmsCodeService'])) {
            return $container->privates['App\\Service\\SmsCodeService'];
        }

        $instance = new \App\Service\SmsCodeService(($container->services['cache.app'] ?? $container->load('getCache_AppService')), $a);

        if (isset($container->privates['App\\Service\\SmsCodeService'])) {
            return $container->privates['App\\Service\\SmsCodeService'];
        }

        return $container->privates['App\\Service\\SmsCodeService'] = $instance;
    }
}
