<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX9vLmXo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX9vLmXo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX9vLmXo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX9vLmXo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX9vLmXo\App_KernelDevDebugContainer([
    'container.build_hash' => 'X9vLmXo',
    'container.build_id' => '297a83be',
    'container.build_time' => 1776553430,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX9vLmXo');
