<?php

namespace ContainerX9vLmXo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LAaZIl0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lAaZIl0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminLivraisonController::affecter' => ['privates', '.service_locator.wE7thEd', 'get_ServiceLocator_WE7thEdService', true],
            'App\\Controller\\AdminLivraisonController::cancelFirstDelivery' => ['privates', '.service_locator.bC.pni8', 'get_ServiceLocator_BC_Pni8Service', true],
            'App\\Controller\\AdminLivraisonController::details' => ['privates', '.service_locator.ttXmCFl', 'get_ServiceLocator_TtXmCFlService', true],
            'App\\Controller\\AdminLivraisonController::index' => ['privates', '.service_locator.0Pxg7rx', 'get_ServiceLocator_0Pxg7rxService', true],
            'App\\Controller\\AdminLivraisonController::markFirstPacked' => ['privates', '.service_locator.bC.pni8', 'get_ServiceLocator_BC_Pni8Service', true],
            'App\\Controller\\AdminLivraisonController::sendToFirstDelivery' => ['privates', '.service_locator.gUv3FSu', 'get_ServiceLocator_GUv3FSuService', true],
            'App\\Controller\\AdminLivraisonController::terminer' => ['privates', '.service_locator.9GGJk9h', 'get_ServiceLocator_9GGJk9hService', true],
            'App\\Controller\\AdminLivraisonController::updateStatus' => ['privates', '.service_locator.73s6gac', 'get_ServiceLocator_73s6gacService', true],
            'App\\Controller\\AdminVisitorController::count' => ['privates', '.service_locator.5A2xTDx', 'get_ServiceLocator_5A2xTDxService', true],
            'App\\Controller\\ChatController::chat' => ['privates', '.service_locator.ajErm5Q', 'get_ServiceLocator_AjErm5QService', true],
            'App\\Controller\\FavoriController::index' => ['privates', '.service_locator.4r_CVEk', 'get_ServiceLocator_4rCVEkService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.U8UNK4r', 'get_ServiceLocator_U8UNK4rService', true],
            'App\\Controller\\MessageController::conversation' => ['privates', '.service_locator.FvL2A9p', 'get_ServiceLocator_FvL2A9pService', true],
            'App\\Controller\\MessageController::inbox' => ['privates', '.service_locator.FvL2A9p', 'get_ServiceLocator_FvL2A9pService', true],
            'App\\Controller\\NotificationController::index' => ['privates', '.service_locator.LMyLTbF', 'get_ServiceLocator_LMyLTbFService', true],
            'App\\Controller\\NotificationController::markAsRead' => ['privates', '.service_locator.jxD8HYM', 'get_ServiceLocator_JxD8HYMService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.5A2xTDx', 'get_ServiceLocator_5A2xTDxService', true],
            'App\\Controller\\RegisterController::register' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\ResetPasswordController::forgot' => ['privates', '.service_locator.66gHImX', 'get_ServiceLocator_66gHImXService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::logoutAllDevices' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UnlockController::request' => ['privates', '.service_locator.Ps8D7Wc', 'get_ServiceLocator_Ps8D7WcService', true],
            'App\\Controller\\UnlockController::verify' => ['privates', '.service_locator.esvQdub', 'get_ServiceLocator_EsvQdubService', true],
            'App\\Controller\\UtilisateurController::editer' => ['privates', '.service_locator.8NzCy4M', 'get_ServiceLocator_8NzCy4MService', true],
            'App\\Controller\\UtilisateurController::nouveau' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\UtilisateurController::supprimer' => ['privates', '.service_locator.8NzCy4M', 'get_ServiceLocator_8NzCy4MService', true],
            'App\\Controller\\UtilisateurWebController::exportPdf' => ['privates', '.service_locator._vTtnkj', 'get_ServiceLocator_VTtnkjService', true],
            'App\\Controller\\UtilisateurWebController::monProfil' => ['privates', '.service_locator.r84DuGu', 'get_ServiceLocator_R84DuGuService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminLivraisonController:affecter' => ['privates', '.service_locator.wE7thEd', 'get_ServiceLocator_WE7thEdService', true],
            'App\\Controller\\AdminLivraisonController:cancelFirstDelivery' => ['privates', '.service_locator.bC.pni8', 'get_ServiceLocator_BC_Pni8Service', true],
            'App\\Controller\\AdminLivraisonController:details' => ['privates', '.service_locator.ttXmCFl', 'get_ServiceLocator_TtXmCFlService', true],
            'App\\Controller\\AdminLivraisonController:index' => ['privates', '.service_locator.0Pxg7rx', 'get_ServiceLocator_0Pxg7rxService', true],
            'App\\Controller\\AdminLivraisonController:markFirstPacked' => ['privates', '.service_locator.bC.pni8', 'get_ServiceLocator_BC_Pni8Service', true],
            'App\\Controller\\AdminLivraisonController:sendToFirstDelivery' => ['privates', '.service_locator.gUv3FSu', 'get_ServiceLocator_GUv3FSuService', true],
            'App\\Controller\\AdminLivraisonController:terminer' => ['privates', '.service_locator.9GGJk9h', 'get_ServiceLocator_9GGJk9hService', true],
            'App\\Controller\\AdminLivraisonController:updateStatus' => ['privates', '.service_locator.73s6gac', 'get_ServiceLocator_73s6gacService', true],
            'App\\Controller\\AdminVisitorController:count' => ['privates', '.service_locator.5A2xTDx', 'get_ServiceLocator_5A2xTDxService', true],
            'App\\Controller\\ChatController:chat' => ['privates', '.service_locator.ajErm5Q', 'get_ServiceLocator_AjErm5QService', true],
            'App\\Controller\\FavoriController:index' => ['privates', '.service_locator.4r_CVEk', 'get_ServiceLocator_4rCVEkService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.U8UNK4r', 'get_ServiceLocator_U8UNK4rService', true],
            'App\\Controller\\MessageController:conversation' => ['privates', '.service_locator.FvL2A9p', 'get_ServiceLocator_FvL2A9pService', true],
            'App\\Controller\\MessageController:inbox' => ['privates', '.service_locator.FvL2A9p', 'get_ServiceLocator_FvL2A9pService', true],
            'App\\Controller\\NotificationController:index' => ['privates', '.service_locator.LMyLTbF', 'get_ServiceLocator_LMyLTbFService', true],
            'App\\Controller\\NotificationController:markAsRead' => ['privates', '.service_locator.jxD8HYM', 'get_ServiceLocator_JxD8HYMService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.5A2xTDx', 'get_ServiceLocator_5A2xTDxService', true],
            'App\\Controller\\RegisterController:register' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\ResetPasswordController:forgot' => ['privates', '.service_locator.66gHImX', 'get_ServiceLocator_66gHImXService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:logoutAllDevices' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UnlockController:request' => ['privates', '.service_locator.Ps8D7Wc', 'get_ServiceLocator_Ps8D7WcService', true],
            'App\\Controller\\UnlockController:verify' => ['privates', '.service_locator.esvQdub', 'get_ServiceLocator_EsvQdubService', true],
            'App\\Controller\\UtilisateurController:editer' => ['privates', '.service_locator.8NzCy4M', 'get_ServiceLocator_8NzCy4MService', true],
            'App\\Controller\\UtilisateurController:nouveau' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\UtilisateurController:supprimer' => ['privates', '.service_locator.8NzCy4M', 'get_ServiceLocator_8NzCy4MService', true],
            'App\\Controller\\UtilisateurWebController:exportPdf' => ['privates', '.service_locator._vTtnkj', 'get_ServiceLocator_VTtnkjService', true],
            'App\\Controller\\UtilisateurWebController:monProfil' => ['privates', '.service_locator.r84DuGu', 'get_ServiceLocator_R84DuGuService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminLivraisonController::affecter' => '?',
            'App\\Controller\\AdminLivraisonController::cancelFirstDelivery' => '?',
            'App\\Controller\\AdminLivraisonController::details' => '?',
            'App\\Controller\\AdminLivraisonController::index' => '?',
            'App\\Controller\\AdminLivraisonController::markFirstPacked' => '?',
            'App\\Controller\\AdminLivraisonController::sendToFirstDelivery' => '?',
            'App\\Controller\\AdminLivraisonController::terminer' => '?',
            'App\\Controller\\AdminLivraisonController::updateStatus' => '?',
            'App\\Controller\\AdminVisitorController::count' => '?',
            'App\\Controller\\ChatController::chat' => '?',
            'App\\Controller\\FavoriController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\MessageController::conversation' => '?',
            'App\\Controller\\MessageController::inbox' => '?',
            'App\\Controller\\NotificationController::index' => '?',
            'App\\Controller\\NotificationController::markAsRead' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\RegisterController::register' => '?',
            'App\\Controller\\ResetPasswordController::forgot' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::logoutAllDevices' => '?',
            'App\\Controller\\UnlockController::request' => '?',
            'App\\Controller\\UnlockController::verify' => '?',
            'App\\Controller\\UtilisateurController::editer' => '?',
            'App\\Controller\\UtilisateurController::nouveau' => '?',
            'App\\Controller\\UtilisateurController::supprimer' => '?',
            'App\\Controller\\UtilisateurWebController::exportPdf' => '?',
            'App\\Controller\\UtilisateurWebController::monProfil' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminLivraisonController:affecter' => '?',
            'App\\Controller\\AdminLivraisonController:cancelFirstDelivery' => '?',
            'App\\Controller\\AdminLivraisonController:details' => '?',
            'App\\Controller\\AdminLivraisonController:index' => '?',
            'App\\Controller\\AdminLivraisonController:markFirstPacked' => '?',
            'App\\Controller\\AdminLivraisonController:sendToFirstDelivery' => '?',
            'App\\Controller\\AdminLivraisonController:terminer' => '?',
            'App\\Controller\\AdminLivraisonController:updateStatus' => '?',
            'App\\Controller\\AdminVisitorController:count' => '?',
            'App\\Controller\\ChatController:chat' => '?',
            'App\\Controller\\FavoriController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\MessageController:conversation' => '?',
            'App\\Controller\\MessageController:inbox' => '?',
            'App\\Controller\\NotificationController:index' => '?',
            'App\\Controller\\NotificationController:markAsRead' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\RegisterController:register' => '?',
            'App\\Controller\\ResetPasswordController:forgot' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:logoutAllDevices' => '?',
            'App\\Controller\\UnlockController:request' => '?',
            'App\\Controller\\UnlockController:verify' => '?',
            'App\\Controller\\UtilisateurController:editer' => '?',
            'App\\Controller\\UtilisateurController:nouveau' => '?',
            'App\\Controller\\UtilisateurController:supprimer' => '?',
            'App\\Controller\\UtilisateurWebController:exportPdf' => '?',
            'App\\Controller\\UtilisateurWebController:monProfil' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.lAaZIl0'])) {
            return $container->privates['.service_locator.lAaZIl0'];
        }

        return $container->privates['.service_locator.lAaZIl0'] = $instance;
    }
}
