<?php

namespace ContainerX9vLmXo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminAbandonedCommandeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AdminAbandonedCommandeController' shared autowired service.
     *
     * @return \App\Controller\AdminAbandonedCommandeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AdminAbandonedCommandeController.php';

        $container->services['App\\Controller\\AdminAbandonedCommandeController'] = $instance = new \App\Controller\AdminAbandonedCommandeController(($container->privates['App\\Repository\\AbandonedCommandeRepository'] ?? $container->load('getAbandonedCommandeRepositoryService')), ($container->privates['App\\Repository\\ProduitRepository'] ?? $container->load('getProduitRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\AdminAbandonedCommandeController', $container));

        return $instance;
    }
}
