<?php

namespace ContainerX9vLmXo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginAttemptServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\LoginAttemptService' shared autowired service.
     *
     * @return \App\Security\LoginAttemptService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'LoginAttemptService.php';

        return $container->privates['App\\Security\\LoginAttemptService'] = new \App\Security\LoginAttemptService(($container->services['cache.app'] ?? $container->load('getCache_AppService')));
    }
}
