<?php

namespace ContainerX9vLmXo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginBlockSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\LoginBlockSubscriber' shared autowired service.
     *
     * @return \App\Security\LoginBlockSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'LoginBlockSubscriber.php';

        return $container->privates['App\\Security\\LoginBlockSubscriber'] = new \App\Security\LoginBlockSubscriber(($container->privates['App\\Security\\LoginAttemptService'] ?? $container->load('getLoginAttemptServiceService')));
    }
}
