<?php

namespace ContainerX9vLmXo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatPublicControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PlatPublicController' shared autowired service.
     *
     * @return \App\Controller\PlatPublicController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'PlatPublicController.php';

        $container->services['App\\Controller\\PlatPublicController'] = $instance = new \App\Controller\PlatPublicController(($container->privates['App\\Repository\\PlatRepository'] ?? $container->load('getPlatRepositoryService')), ($container->privates['App\\Repository\\PartenaireRepository'] ?? $container->load('getPartenaireRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PlatPublicController', $container));

        return $instance;
    }
}
